CREATE TABLE IF NOT EXISTS question (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  text TEXT NOT NULL UNIQUE,
  topic TEXT NOT NULL
);

INSERT OR REPLACE INTO question (id, text, topic) VALUES
(1, 'We have our own individual software, how do we get it into the cloud?', 'Cloud Services'),
(2, 'How can we modernize our software', 'Cloud Services'),
(3, 'How can I start using cloud services', 'Cloud Services'),
(4, 'What is the path to the cloud for my company', 'Cloud Services'),
(5, 'Who owns my data in the cloud', 'Cloud Services'),
(6, 'Which cloud model is right for us', 'Cloud Services'),
(7, 'Which public cloud provider is the right one for my company', 'Cloud Services'),
(8, 'Can I only use individual cloud services', 'Cloud Services'),
(9, 'As a small company, can we take advantage of the cloud', 'Cloud Services'),
(10, 'How can I access my data from anywhere', 'Cloud Services'),
(11, 'We want to make digital business ideas more agile, what infrastructure do we need', 'Cloud Services'),
(12, 'Is my data secure in the cloud', 'Cloud Services'),
(13, 'What about data protection with public cloud providers', 'Cloud Services'),
(14, 'How do I migrate my existing data to the cloud', 'Cloud Services'),
(15, 'Can I encrypt my data in the cloud', 'Cloud Services'),
(16, 'Which data/services can I move to the cloud', 'Cloud Services'),
(17, 'What advantages can the cloud bring me', 'Cloud Services'),
(18, 'Do I still need my own server', 'Cloud Services'),
(19, 'Do I still need the daily tape backup', 'Cloud Services'),
(20, 'The server room needs too much space, can I release the space thanks to the cloud', 'Cloud Services'),
(21, 'Our servers are already old, is it worth buying a new one', 'Cloud Services'),
(22, 'Is my data secure in the cloud', 'Cloud Services'),
(23, 'I want to be able to access business data on the move, is the cloud suitable for this', 'Cloud Services'),
(24, 'I have all my data in the cloud, but now I want my own server HW, how do I proceed', 'Cloud Services'),
(25, 'How long does a cloud transformation take', 'Cloud Services'),
(26, 'Do I have to move everything to the cloud or is it only possible to move individual data/services', 'Cloud Services'),
(27, 'Which cloud providers can you recommend', 'Cloud Services'),
(28, 'What are cloud services? I only know Dropbox, i.e. Data Cloud.', 'Cloud Services'),
(29, 'Can I run my own cloud with us on our servers?', 'Cloud Services'),
(30, 'Is cloud cheap?', 'Cloud Services'),
(31, 'Our workstations are outdated, are there cloud solutions for employee PCs and not just servers?', 'Cloud Services'),
(32, 'Installing and updating our software is error-prone and time-consuming. How can we optimize this?', 'Cloud Services'),
(33, 'We are planning a company move, should we also move to the cloud at the same time?', 'Cloud Services'),
(34, 'Can we make our IT staff redundant thanks to cloud solutions?', 'Cloud Services'),
(35, 'How can we offer our customers and ourselves a high level of continuity?', 'Cloud Services'),
(36, 'We need to ensure that in the event of a problem, our data can be recovered as quickly as possible, how best?', 'Cloud Services'),
(37, 'How can we optimize our backup & restore process?', 'Cloud Services'),
(38, 'Which preventive measures regarding continuity are suitable for our IT?', 'Cloud Services'),
(39, 'Our own servers are often not available, how can we achieve better availability?', 'Cloud Services'),
(40, 'We can close down our company if we lose data, how can we protect ourselves from loss?', 'Cloud Services'),
(41, 'We have a product idea, how do we start?', 'Digitale Product'),
(42, 'We have an idea, is it technically feasible?', 'Digitale Product'),
(43, 'We have an idea, what costs do we have to expect?', 'Digitale Product'),
(44, 'How can we sell our software product as SaaS?', 'Digitale Product'),
(45, 'We have an idea for a digital product, do comparable products already exist?', 'Digitale Product'),
(46, 'Is it even possible to implement our idea with current technology?', 'Digitale Product'),
(47, 'How can I sell a digital product?', 'Digitale Product'),
(48, 'We sell analogue products and want to complement them with digital elements. How do we turn them into products 2.0?', 'Digitale Product'),
(49, 'What is the path from idea to implementation?', 'Digitale Product'),
(50, 'We sell trees, can we develop a digital product to sell even more trees?', 'Digitale Product'),
(51, 'We sell analog/real products but want to be hip and attract young customers, what are the possibilities?', 'Digitale Product'),
(52, 'We have an analogue product and want to create a digital (accompanying) product for it. Just like the SNB App for the new sheet music.', 'Digitale Product'),
(53, 'Everywhere I read about digitisation, how can I start?', 'Digitalisierung'),
(54, 'The digital world is a black hole for us, how do we get started?', 'Digitalisierung'),
(55, 'Can we digitise our paper correspondence?', 'Digitalisierung'),
(56, 'We are increasingly losing ground to our counterparts, how can we counteract this?', 'Digitalisierung'),
(57, 'Our suppliers/partners want to modernize conventional interfaces, how can we keep up?', 'Digitalisierung'),
(58, 'Does our business model also work in the digital world?', 'Digitalisierung'),
(59, 'What opportunities does digitization offer us?', 'Digitalisierung'),
(60, 'What are the dangers of digitization?', 'Digitalisierung'),
(61, 'Do we have to digitize as a whole or can we convert individual parts step by step?', 'Digitalisierung'),
(62, 'Does your individual software also come with individual SLAs?', 'Individuelle SLA'),
(63, 'What happens after a possible development?', 'Individuelle SLA'),
(64, 'Do you offer different SLAs?', 'Individuelle SLA'),
(65, 'Do you create an SLA for our own development?', 'Individuelle SLA'),
(66, 'Can you help us with the creation of SLAs?', 'Individuelle SLA'),
(67, 'What about the maintenance of individual software?', 'Individuelle SLA'),
(68, 'Do you also take care of the maintenance of the individual software?', 'Individuelle SLA'),
(69, 'Is a software project finished with acceptance?', 'Individuelle SLA'),
(70, 'Will the software you have developed still work in three years?', 'Individuelle SLA'),
(71, 'We have developed our own sensor hardware, how can we efficiently process the resulting information?', 'IOT'),
(72, 'How can I manage my IOT devices?', 'IOT'),
(73, 'How can we create a platform on which to use IOT?', 'IOT'),
(74, 'Where is the self-shopping refrigerator?', 'IOT'),
(75, 'How can we facilitate the remote maintenance of our products?', 'IOT'),
(76, 'Our products collect data, how can we process and link them?', 'IOT'),
(77, 'How do we connect our product to the Internet?', 'IOT'),
(78, 'I want to know where our products are, how can I do that?', 'IOT'),
(79, 'What new business models does IoT enable?', 'IOT'),
(80, 'Why is our IT so expensive?', 'Cutting Costs'),
(81, 'How can I reduce IT costs?', 'Cutting Costs'),
(82, 'Our software is far too expensive to run and maintain, what can we change?', 'Cutting Costs'),
(83, 'Is our IT too expensive?', 'Cutting Costs'),
(84, 'How can we reduce our costs?', 'Cutting Costs'),
(85, 'Our IT costs a lot, but we don''t know why?', 'Cutting Costs'),
(86, 'We want to set up our own development, what costs can we expect?', 'Cutting Costs'),
(87, 'Every second year we pay a huge sum for new hardware, how can we reduce these costs?', 'Cutting Costs'),
(88, 'Everyone talks about cost reduction through cloud services, but what are the costs?', 'Cutting Costs'),
(89, 'How much does it cost to get to the cloud?', 'Cutting Costs'),
(90, 'Why is IT expensive?', 'Cutting Costs'),
(91, 'How can we charge and prove our development time to the customer?', 'Cutting Costs'),
(92, 'How can the development time of an application be reduced?', 'Cutting Costs'),
(93, 'We would like to relieve (or actually dismiss) our support staff, can this be done with the help of artificial intelligence?', 'AI / ML'),
(94, 'Can we make our (not only digital) products more intelligent?', 'AI / ML'),
(95, 'Can we speed up and improve our product repair/replacement with customer photos?', 'AI / ML'),
(96, 'Can we repair faults more quickly with the help of artificial intelligence?', 'AI / ML'),
(97, 'How can we locate and automate simple repetitive tasks/requests?', 'AI / ML'),
(98, 'We have collected a lot of data but don''t know what we can do with it.', 'AI / ML'),
(99, 'Can I find a consensus with swarm intelligence?', 'AI / ML'),
(100, 'How can I protect myself and my products from AI and MI (Bots) comments, ratings?', 'AI / ML'),
(101, 'I want our customers to be able to control our products with language, how does that work?', 'AI / ML'),
(102, 'I want our customers to be able to control our products with gestures, how does that work?', 'AI / ML'),
(103, 'Our system should be able to recognize our products by means of photos.', 'AI / ML'),
(104, 'Many websites offer annoying chat bots, how can we do this better?', 'AI / ML'),
(105, 'I have read No UI is the new UI what does this mean?', 'AI / ML'),
(106, 'I think chat bots are cool but what kind of interactions are they really for?', 'AI / ML'),
(107, 'Can we add a chat bot to our internal WIKI?', 'AI / ML'),
(108, 'The chat bot as user interface, how does it work?', 'AI / ML'),
(109, 'We want to answer customer inquiries as automatically as possible, is that possible?', 'AI / ML'),
(110, 'We often receive similar requests and would like to answer them automatically, is that possible?', 'AI / ML'),
(111, 'I have an idea but nobody understands what I mean, can you build a prototype?', 'Prototyping'),
(112, 'I want to present something tangible to the board as soon as possible?', 'Prototyping'),
(113, 'Our customers should already have a taste of the new product, what is suitable for this?', 'Prototyping'),
(114, 'I have an idea, but I can''t imagine what it might actually look like.', 'Prototyping'),
(115, 'I can''t imagine what our application feels like on a smartphone.', 'Prototyping'),
(116, 'We already have a design but can''t imagine what it will look like later.', 'Prototyping'),
(117, 'I want to test my idea with potential customers.', 'Prototyping'),
(118, 'I want to get feedback on my idea as soon as possible.', 'Prototyping'),
(119, 'We want to validate our concept (PoC) as soon as possible.', 'Prototyping'),
(120, 'Employee entrys/exits are tedious for IT, how can we optimize this process?', 'Process Design'),
(121, 'Time recording is cumbersome, how can we optimize this process?', 'Process Design'),
(122, 'The sending of invoices is opaque/incomplete and time-consuming, are there optimization possibilities?', 'Process Design'),
(123, 'Internal communication is limited, how can we improve it?', 'Process Design'),
(124, 'Customer communication is not always comprehensible, how do we improve contact with our customers?', 'Process Design'),
(125, 'We would like to use less paper, how could we achieve this?', 'Process Design'),
(126, 'Our projects always end in chaos, how and with which tools can we organize ourselves better?', 'Process Design'),
(127, 'Which processes can we outsource, e.g. to third parties or to the cloud?', 'Process Design'),
(128, 'We don''t even know what our customers think of our products, how do we get customer feedback?', 'Process Design'),
(129, 'We would like to make less phone calls, how can we achieve this?', 'Process Design'),
(130, 'We would like to increase our efficiency, but don''t know how.', 'Process Design'),
(131, 'We don''t know if we need online channels in addition to our offline channels?', 'Process Design'),
(132, 'We suddenly have to be global and compete, how do we optimize our processes for the global market?', 'Process Design'),
(133, 'Many customers, i.e. the digital natives, only want to contact us online, how can we build up/improve the digital customer experience?', 'Process Design'),
(134, 'How can we integrate potential customers or Internet users into our processes, i.e. develop products with them?', 'Process Design'),
(135, 'The customer as a source of ideas is that possible?', 'Process Design'),
(136, 'How can I link different online services?', 'Second Opinion'),
(137, 'How can I link my internal IT with new cloud services?', 'Second Opinion'),
(138, 'We have found a service that does exactly what we need, how can we use/integrate it?', 'Second Opinion'),
(139, 'How can we integrate different services to provide the desired overall functionality?', 'Second Opinion'),
(140, 'We want to offer our partners an interface to our system, how can we do this?', 'Second Opinion'),
(141, 'How can we offer our processes/services to others?', 'Second Opinion'),
(142, 'How can we replace our existing service, migrate and integrate a new service?', 'Second Opinion'),
(143, 'When is it worthwhile to create a complete application because otherwise too many different services have to be integrated?', 'Second Opinion'),
(144, 'Help we need too many different services.', 'Second Opinion'),
(145, 'Can we consolidate services X, Z, Y and W to work in our environment?', 'Second Opinion'),
(146, 'We would like to automate certain processes, how is that possible?', 'Second Opinion'),
(147, 'How can we be informed when one of our applications has produced an error?', 'Second Opinion'),
(148, 'We need an implementation partner for our project?', 'Software Entwicklung'),
(149, 'Do I still have to develop Android and iOS apps today?', 'Software Entwicklung'),
(150, 'Are there alternatives to the app?', 'Software Entwicklung'),
(151, 'We have our own app and would like to replace/update it.', 'Software Entwicklung'),
(152, 'How many employees are you?', 'Team'),
(153, 'How many people work at shiftcode?', 'Team'),
(154, 'How many are you?', 'Team'),
(155, 'Do you like table tennis?', 'We really like table tennis.'),
(156, 'How big are you?', 'Team'),
(157, 'Do you offer support after implementation?', 'Third Level Support'),
(158, 'Are you developing error-free software?', 'Third Level Support'),
(159, 'Should problems occur during the operation of the software, who will help us?', 'Third Level Support'),
(160, 'We are looking for external specialists who can help us with more complex IT problems.', 'Third Level Support'),
(161, 'We often have problems with our application but don''t know why, can you analyze it for us?', 'Third Level Support'),
(162, 'We are looking for someone who can solve a problem with the specialists of manufacturer XY of our software/HW.', 'Third Level Support'),
(163, 'We are dissatisfied with manufacturer/company XY and are looking for a new support partner for our applications.', 'Third Level Support'),
(164, 'I have an offer, can you check it?', 'Second Opinion'),
(165, 'Can I get a second opinion from you?', 'Second Opinion'),
(166, 'Our project will be finished soon - can you accompany our company during the acceptance?', 'Second Opinion'),
(167, 'A technology has been suggested for the implementation, is it useful for our project?', 'Second Opinion'),
(168, 'Is there an alternative solution for my project?', 'Second Opinion'),
(169, 'Is the proposed solution future-oriented?', 'Second Opinion'),
(170, 'Does this company work with current technologies?', 'Second Opinion'),
(171, 'Does the solution meet modern standards?', 'Second Opinion'),
(172, 'Does the solution make sense at all?', 'Second Opinion'),
(173, 'Does it need all proposed parts/areas of the solution?', 'Second Opinion'),
(174, 'Is the offer complete or have parts not been considered?', 'Second Opinion'),
(175, 'Does the quote include hidden costs?', 'Second Opinion'),
(176, 'Is the offered solution secure?', 'Second Opinion'),
(177, 'Is the offered solution expandable?', 'Second Opinion'),
(178, 'Is the offered solution much too expensive?', 'Second Opinion'),
(179, 'We have a meeting with an implementation partner, can you accompany us as an external third party? ', 'Second Opinion'),
(180, 'Are we on the right track with the implementation?', 'Second Opinion'),
(181, 'Does what we have achieved so far also correspond to the solution we have offered?', 'Second Opinion'),
(182, 'The cooperation does not work as desired, do you help us to find a new partner?', 'Second Opinion'),
(183, 'The cooperation does not work as desired, do you help us to offer you a new partner?', 'Second Opinion'),
(184, 'The cooperation does not work as desired, can you take over the implementation of the project?', 'Second Opinion'),
(185, 'We were recommended (standard) product XY, does this meet our needs?', 'Second Opinion'),
(186, 'We were recommended (standard) product XY, is the product good?', 'Second Opinion'),
(187, 'We are of the opinion that our requirements have not been fully implemented, but have too little technical understanding of the solution and need help.', 'Second Opinion'),
(188, 'Give us your opinion about our IT architecture/landscape.', 'Second Opinion'),
(189, 'We need help interviewing a new IT employee.', 'Second Opinion'),
(190, 'Which app is suitable for <topic>?', 'Second Opinion');
